.nh
.TH "GH-PROJECT-ITEM-ARCHIVE" "1" "Dec 2023" "GitHub CLI 2.40.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-item-archive - Archive an item in a project


.SH SYNOPSIS
.PP
\fBgh project item-archive [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB--id\fR \fB<string>\fR
ID of the item to archive

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB--undo\fR
Unarchive an item


.SH EXAMPLE
.EX
# archive an item in the current user's project "1"
gh project item-archive 1 --owner "@me" --id <item-ID>


.EE


.SH SEE ALSO
.PP
\fBgh-project(1)\fR
