.nh
.TH "GH-PROJECT-ITEM-CREATE" "1" "Dec 2023" "GitHub CLI 2.40.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-item-create - Create a draft issue item in a project


.SH SYNOPSIS
.PP
\fBgh project item-create [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--body\fR \fB<string>\fR
Body for the draft issue

.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB--title\fR \fB<string>\fR
Title for the draft issue


.SH EXAMPLE
.EX
# create a draft issue in the current user's project "1"
gh project item-create 1 --owner "@me" --title "new item" --body "new item body"


.EE


.SH SEE ALSO
.PP
\fBgh-project(1)\fR
