.nh
.TH "GH-RELEASE-LIST" "1" "Dec 2023" "GitHub CLI 2.40.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release-list - List releases in a repository


.SH SYNOPSIS
.PP
\fBgh release list [flags]\fR


.SH OPTIONS
.TP
\fB--exclude-drafts\fR
Exclude draft releases

.TP
\fB--exclude-pre-releases\fR
Exclude pre-releases

.TP
\fB-L\fR, \fB--limit\fR \fB<int>\fR
Maximum number of items to fetch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-release(1)\fR
